import Link from "next/link"
import "./styles/global.css"
import Image from "next/image"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <main>
          <nav>
            <Link href='/'>
              <Image
                src="/giphy.gif"
                width={75}
                height={75}
                alt="Picture of the author"
              />
            </Link>
            <Link href='/proyectos'>proyectos</Link>
            <Link href='/coleccion'>colección</Link>
          </nav>
          {children}
        </main>
      </body>
    </html>
  )
}
